import type { DashboardSnapshot } from '../types/crm'

export const crmDemoData: DashboardSnapshot = {
  source: 'demo',
  message:
    'Supabase is not connected yet. The CRM is showing a realistic institute dataset so you can shape the experience before wiring live data.',
  lastSyncedAt: new Date().toISOString(),
  metrics: [
    {
      id: 'families',
      label: 'Families in nurture flow',
      value: '128',
      change: '+14 this month',
      detail: 'Tour interest is strongest for preschool and pre-k.',
      tone: 'teal',
    },
    {
      id: 'enrollment',
      label: 'Enrollment conversion',
      value: '62%',
      change: '+8 pts since Feb',
      detail: 'Tour-to-application follow-up is improving within 48 hours.',
      tone: 'coral',
    },
    {
      id: 'attendance',
      label: 'Average attendance',
      value: '93%',
      change: '+3 pts this week',
      detail: 'Toddler and pre-k rooms are trending above target.',
      tone: 'amber',
    },
    {
      id: 'retention',
      label: 'Family retention outlook',
      value: '96%',
      change: '4 renewals pending',
      detail: 'Spring re-enrollment calls are scheduled for the next 7 days.',
      tone: 'plum',
    },
  ],
  leads: [
    {
      id: 'lead-alvarez',
      familyName: 'Alvarez',
      childName: 'Mila',
      programInterest: 'Preschool Discovery',
      stage: 'Tour Booked',
      source: 'Website inquiry',
      followUpDate: '2026-03-15',
      priority: 'High',
      campus: 'Edina',
      ageGroup: '3 years',
      nextStep: 'Confirm tour packet and allergy form.',
    },
    {
      id: 'lead-thompson',
      familyName: 'Thompson',
      childName: 'Noah',
      programInterest: 'Infant Nurture Studio',
      stage: 'Inquiry',
      source: 'Referral partner',
      followUpDate: '2026-03-14',
      priority: 'High',
      campus: 'Edina',
      ageGroup: '8 months',
      nextStep: 'Call back with tuition guide and schedule options.',
    },
    {
      id: 'lead-chen',
      familyName: 'Chen',
      childName: 'Ivy',
      programInterest: 'Pre-K Readiness',
      stage: 'Application Started',
      source: 'Instagram ad',
      followUpDate: '2026-03-16',
      priority: 'Medium',
      campus: 'Edina',
      ageGroup: '4 years',
      nextStep: 'Review vaccination records and finalize start week.',
    },
    {
      id: 'lead-okafor',
      familyName: 'Okafor',
      childName: 'Ethan',
      programInterest: 'Toddler Explorers',
      stage: 'Waitlist',
      source: 'Open house',
      followUpDate: '2026-03-18',
      priority: 'Medium',
      campus: 'Edina',
      ageGroup: '2 years',
      nextStep: 'Offer next available slot and payment plan options.',
    },
    {
      id: 'lead-patel',
      familyName: 'Patel',
      childName: 'Aanya',
      programInterest: 'Pre-K Readiness',
      stage: 'Enrolled',
      source: 'Website inquiry',
      followUpDate: '2026-03-13',
      priority: 'Low',
      campus: 'Edina',
      ageGroup: '5 years',
      nextStep: 'Send welcome pack and family onboarding checklist.',
    },
    {
      id: 'lead-johnson',
      familyName: 'Johnson',
      childName: 'Leo',
      programInterest: 'Toddler Explorers',
      stage: 'Tour Booked',
      source: 'Google search',
      followUpDate: '2026-03-17',
      priority: 'Medium',
      campus: 'Edina',
      ageGroup: '18 months',
      nextStep: 'Prepare speech support resources for family questions.',
    },
  ],
  students: [
    {
      id: 'student-walker',
      name: 'Harper Walker',
      guardian: 'Sofia Walker',
      program: 'Preschool Discovery',
      attendance: '98%',
      pickupWindow: '5:15 PM',
      supportFocus: 'Social confidence in group play',
      tuitionStatus: 'Current',
      milestone: 'Leading circle-time storytelling.',
    },
    {
      id: 'student-khan',
      name: 'Aarav Khan',
      guardian: 'Nadia Khan',
      program: 'Pre-K Readiness',
      attendance: '94%',
      pickupWindow: '4:45 PM',
      supportFocus: 'Early literacy reinforcement',
      tuitionStatus: 'Review',
      milestone: 'Recognizes all uppercase letters.',
    },
    {
      id: 'student-garcia',
      name: 'Luna Garcia',
      guardian: 'Miguel Garcia',
      program: 'Toddler Explorers',
      attendance: '91%',
      pickupWindow: '5:30 PM',
      supportFocus: 'Nap transition consistency',
      tuitionStatus: 'Current',
      milestone: 'Transitioning independently between centers.',
    },
    {
      id: 'student-brown',
      name: 'Ezra Brown',
      guardian: 'Maya Brown',
      program: 'Infant Nurture Studio',
      attendance: '96%',
      pickupWindow: '4:20 PM',
      supportFocus: 'Feeding rhythm tracking',
      tuitionStatus: 'Current',
      milestone: 'New sensory exploration plan started this week.',
    },
  ],
  programs: [
    {
      id: 'program-infant',
      name: 'Infant Nurture Studio',
      ageRange: '6 weeks to 14 months',
      capacity: '16 seats',
      fillRate: 88,
      leads: 9,
      waitlist: 3,
      educators: ['Mina P.', 'Jordan K.'],
      description:
        'Warm care, parent touchpoints, and developmental note tracking for the youngest families.',
    },
    {
      id: 'program-toddler',
      name: 'Toddler Explorers',
      ageRange: '15 months to 2.5 years',
      capacity: '20 seats',
      fillRate: 95,
      leads: 11,
      waitlist: 6,
      educators: ['Sasha L.', 'Daniel A.'],
      description:
        'Movement-rich classrooms with transition routines, sensory play, and language-building moments.',
    },
    {
      id: 'program-preschool',
      name: 'Preschool Discovery',
      ageRange: '3 to 4 years',
      capacity: '24 seats',
      fillRate: 82,
      leads: 14,
      waitlist: 2,
      educators: ['Camila R.', 'Nina W.'],
      description:
        'Project-based learning with family updates, milestone snapshots, and tour-ready classroom storytelling.',
    },
    {
      id: 'program-prek',
      name: 'Pre-K Readiness',
      ageRange: '4 to 5 years',
      capacity: '18 seats',
      fillRate: 90,
      leads: 10,
      waitlist: 4,
      educators: ['Grace F.', 'Anthony B.'],
      description:
        'Kindergarten preparation with literacy, math confidence, and parent-facing progress reporting.',
    },
  ],
  tasks: [
    {
      id: 'task-tour-packets',
      title: 'Send tour packets to the next three high-intent families.',
      owner: 'Admissions',
      dueDate: '2026-03-13',
      status: 'Today',
      priority: 'High',
      category: 'Enrollment',
    },
    {
      id: 'task-reenrollment',
      title: 'Call renewal families whose contracts expire in April.',
      owner: 'Director',
      dueDate: '2026-03-14',
      status: 'This Week',
      priority: 'Medium',
      category: 'Retention',
    },
    {
      id: 'task-attendance',
      title: 'Review attendance trend dips for toddler room after lunch.',
      owner: 'Operations',
      dueDate: '2026-03-15',
      status: 'This Week',
      priority: 'Medium',
      category: 'Operations',
    },
    {
      id: 'task-family-care',
      title: 'Follow up with the Khan family on literacy support resources.',
      owner: 'Family Care',
      dueDate: '2026-03-13',
      status: 'Today',
      priority: 'High',
      category: 'Family Care',
    },
  ],
  activities: [
    {
      id: 'activity-1',
      title: 'Family tour booked',
      description: 'The Alvarez family confirmed a Friday morning tour for Mila.',
      time: '10 minutes ago',
      tag: 'Admissions',
      tone: 'teal',
    },
    {
      id: 'activity-2',
      title: 'Progress note shared',
      description: 'Harper Walker’s classroom note was delivered to her guardian.',
      time: '45 minutes ago',
      tag: 'Student Success',
      tone: 'amber',
    },
    {
      id: 'activity-3',
      title: 'Waitlist seat opened',
      description: 'A toddler seat opens next month. Ethan Okafor is next in line.',
      time: '2 hours ago',
      tag: 'Capacity',
      tone: 'coral',
    },
    {
      id: 'activity-4',
      title: 'Renewal conversation complete',
      description: 'The Walker family confirmed summer continuation and fall renewal.',
      time: 'Today',
      tag: 'Retention',
      tone: 'plum',
    },
  ],
}
