import type { UserPortalState } from '../types/userPortal'

function buildProgressLabel(doneCount: number, totalCount: number) {
  return `${doneCount} of ${totalCount} steps complete`
}

export function createInitialUserPortalState(): UserPortalState {
  return {
    activeChildId: 'child-1',
    selectedThreadId: 'thread-1',
    autopayEnabled: true,
    paymentMethod: 'Visa ending 1842',
    children: [
      {
        id: 'child-1',
        name: 'Aarav Nair',
        program: 'Early Years Launch',
        ageBand: '4 years',
        teacher: 'Teacher Amara',
        attendanceRate: '96%',
        todayStatus: 'Checked in at 8:42 AM',
        pickupWindow: '4:45 PM to 5:15 PM',
        milestone: 'Reading blends with confidence',
        campus: 'Edina Campus',
        medicalNotes: 'Peanut sensitivity. Inhaler stored with the nurse.',
        authorizedPickupCount: 3,
      },
      {
        id: 'child-2',
        name: 'Myra Nair',
        program: 'Toddler Explorers',
        ageBand: '2 years',
        teacher: 'Teacher Leah',
        attendanceRate: '94%',
        todayStatus: 'Holiday enrichment attendance confirmed',
        pickupWindow: '12:15 PM to 12:45 PM',
        milestone: 'Independent snack cleanup routine',
        campus: 'Maple Grove Campus',
        medicalNotes: 'No active allergies. Nap routine updated this month.',
        authorizedPickupCount: 4,
      },
    ],
    applications: [
      {
        id: 'app-1',
        childId: 'child-2',
        campus: 'Maple Grove Campus',
        program: 'Toddler Explorers',
        submittedAt: 'Submitted Mar 10',
        stage: 'Tour scheduled',
        progressLabel: buildProgressLabel(3, 4),
        steps: [
          { id: 'step-profile', title: 'Child profile', status: 'Done' },
          { id: 'step-docs', title: 'Documents uploaded', status: 'Done' },
          { id: 'step-tour', title: 'Tour booking', status: 'In Progress' },
          { id: 'step-review', title: 'Final review', status: 'Pending' },
        ],
        documents: [
          { id: 'doc-birth', title: 'Birth certificate', status: 'Verified', updatedAt: 'Mar 11' },
          { id: 'doc-immunization', title: 'Immunization form', status: 'Verified', updatedAt: 'Mar 11' },
          { id: 'doc-consent', title: 'Guardian consent', status: 'Uploaded', updatedAt: 'Mar 12' },
        ],
        tourDate: 'Mar 19 · 11:00 AM',
        statusNote: 'Admissions confirmed a toddler program tour with the program lead.',
      },
      {
        id: 'app-2',
        childId: 'child-1',
        campus: 'Edina Campus',
        program: 'Summer Story Lab',
        submittedAt: 'Draft saved Mar 14',
        stage: 'Awaiting documents',
        progressLabel: buildProgressLabel(1, 4),
        steps: [
          { id: 'step-profile', title: 'Child profile', status: 'Done' },
          { id: 'step-docs', title: 'Documents uploaded', status: 'Pending' },
          { id: 'step-tour', title: 'Program preview', status: 'Pending' },
          { id: 'step-review', title: 'Seat confirmation', status: 'Pending' },
        ],
        documents: [
          { id: 'doc-photo', title: 'Child profile photo', status: 'Uploaded', updatedAt: 'Mar 14' },
          { id: 'doc-physician', title: 'Physician form', status: 'Missing', updatedAt: 'Pending' },
          { id: 'doc-consent', title: 'Field trip consent', status: 'Missing', updatedAt: 'Pending' },
        ],
        tourDate: null,
        statusNote: 'Summer lab seat can be reserved once documents are complete.',
      },
    ],
    attendanceEntries: [
      {
        id: 'attendance-1',
        childId: 'child-1',
        day: 'Mon',
        dateLabel: 'Mar 11',
        status: 'Present',
        checkIn: '8:39 AM',
        checkOut: '4:51 PM',
        note: 'Story lab and phonics circle',
      },
      {
        id: 'attendance-2',
        childId: 'child-1',
        day: 'Tue',
        dateLabel: 'Mar 12',
        status: 'Present',
        checkIn: '8:41 AM',
        checkOut: '4:47 PM',
        note: 'Outdoor play and counting garden',
      },
      {
        id: 'attendance-3',
        childId: 'child-1',
        day: 'Wed',
        dateLabel: 'Mar 13',
        status: 'Late check-in',
        checkIn: '9:18 AM',
        checkOut: '4:56 PM',
        note: 'Parent note logged in app',
      },
      {
        id: 'attendance-4',
        childId: 'child-2',
        day: 'Mon',
        dateLabel: 'Mar 11',
        status: 'Present',
        checkIn: '8:47 AM',
        checkOut: '12:12 PM',
        note: 'Sensory play and music',
      },
      {
        id: 'attendance-5',
        childId: 'child-2',
        day: 'Tue',
        dateLabel: 'Mar 12',
        status: 'Present',
        checkIn: '8:46 AM',
        checkOut: '12:18 PM',
        note: 'Outdoor movement circuit',
      },
      {
        id: 'attendance-6',
        childId: 'child-2',
        day: 'Wed',
        dateLabel: 'Mar 13',
        status: 'Holiday enrichment',
        checkIn: 'Optional',
        checkOut: 'Optional',
        note: 'Festival celebration schedule',
      },
    ],
    threads: [
      {
        id: 'thread-1',
        childId: 'child-1',
        name: 'Teacher Amara',
        role: 'Class lead',
        channel: 'Teacher',
        status: 'Open',
        lastMessage: 'I have sent a short home activity in resources.',
        timestamp: '09:47 AM',
        unreadCount: 1,
      },
      {
        id: 'thread-2',
        childId: 'child-2',
        name: 'Admissions Office',
        role: 'Enrollment team',
        channel: 'Admissions',
        status: 'Waiting on you',
        lastMessage: 'Tour slots for next week are now open.',
        timestamp: 'Yesterday',
        unreadCount: 2,
      },
      {
        id: 'thread-3',
        childId: null,
        name: 'Accounts Desk',
        role: 'Billing',
        channel: 'Billing',
        status: 'Open',
        lastMessage: 'Receipt has been issued for February tuition.',
        timestamp: 'Mar 11',
        unreadCount: 0,
      },
    ],
    messages: [
      {
        id: 'message-1',
        threadId: 'thread-1',
        sender: 'school',
        author: 'Teacher Amara',
        body: 'Aarav enjoyed phonics circle and shared story cards today.',
        timestamp: '09:40 AM',
      },
      {
        id: 'message-2',
        threadId: 'thread-1',
        sender: 'parent',
        author: 'You',
        body: 'Great update, thank you. Please share if he needs extra reading practice.',
        timestamp: '09:44 AM',
      },
      {
        id: 'message-3',
        threadId: 'thread-1',
        sender: 'school',
        author: 'Teacher Amara',
        body: 'Will do. I have sent a short home activity in resources.',
        timestamp: '09:47 AM',
      },
      {
        id: 'message-4',
        threadId: 'thread-2',
        sender: 'school',
        author: 'Admissions Office',
        body: 'Tour slots for next week are now open for toddler families.',
        timestamp: 'Yesterday',
      },
      {
        id: 'message-5',
        threadId: 'thread-3',
        sender: 'school',
        author: 'Accounts Desk',
        body: 'Receipt has been issued for February tuition and is ready to download.',
        timestamp: 'Mar 11',
      },
    ],
    invoices: [
      {
        id: 'invoice-1',
        childId: 'child-1',
        title: 'March tuition',
        dueDate: 'Due Mar 20',
        amount: '$480',
        status: 'Due Soon',
        category: 'Tuition',
        receiptReady: false,
      },
      {
        id: 'invoice-2',
        childId: 'child-2',
        title: 'Activity materials',
        dueDate: 'Processing',
        amount: '$45',
        status: 'Pending',
        category: 'Materials',
        receiptReady: false,
      },
      {
        id: 'invoice-3',
        childId: null,
        title: 'February tuition',
        dueDate: 'Paid Mar 02',
        amount: '$480',
        status: 'Paid',
        category: 'Tuition',
        receiptReady: true,
      },
    ],
    events: [
      {
        id: 'event-1',
        childId: 'child-2',
        title: 'Toddler tour window',
        dateLabel: 'Mar 19 · 11:00 AM',
        detail: 'Campus walkthrough for Myra application.',
        category: 'Visit',
      },
      {
        id: 'event-2',
        childId: 'child-1',
        title: 'Spring showcase',
        dateLabel: 'Mar 24 · 4:30 PM',
        detail: 'Family invite for classroom presentation and art wall.',
        category: 'Classroom',
      },
      {
        id: 'event-3',
        childId: null,
        title: 'Invoice reminder',
        dateLabel: 'Mar 20 · All day',
        detail: 'Autopay will trigger if enabled before 5 PM.',
        category: 'Billing',
      },
    ],
    contacts: [
      {
        id: 'contact-1',
        label: 'Primary guardian',
        value: 'Nikhil Nair · +1 612 555 0198',
        type: 'guardian',
      },
      {
        id: 'contact-2',
        label: 'Secondary guardian',
        value: 'Priya Nair · +1 612 555 0156',
        type: 'guardian',
      },
      {
        id: 'contact-3',
        label: 'Emergency pickup',
        value: 'Anita Nair · Verified',
        type: 'pickup',
      },
      {
        id: 'contact-4',
        label: 'Medical consent',
        value: 'Approved and current',
        type: 'medical',
      },
    ],
    resources: [
      {
        id: 'resource-1',
        title: 'Home reading deck',
        detail: 'Short sound-blend practice sent by Teacher Amara.',
        childId: 'child-1',
        category: 'Learning',
      },
      {
        id: 'resource-2',
        title: 'Meal plan this week',
        detail: 'Vegetarian option confirmed for both children.',
        childId: null,
        category: 'Operations',
      },
      {
        id: 'resource-3',
        title: 'Pickup authorization',
        detail: 'Grandparent access expires on Mar 28 unless renewed.',
        childId: null,
        category: 'Safety',
      },
      {
        id: 'resource-4',
        title: 'Fine motor play kit',
        detail: 'Recommended home play extension for Myra.',
        childId: 'child-2',
        category: 'Learning',
      },
    ],
    activityFeed: [
      {
        id: 'activity-1',
        title: 'Receipt downloaded',
        detail: 'February tuition receipt is ready in billing.',
        timestamp: 'Mar 11',
      },
      {
        id: 'activity-2',
        title: 'Reading resource shared',
        detail: 'Teacher Amara added a new practice deck.',
        timestamp: '09:47 AM',
      },
      {
        id: 'activity-3',
        title: 'Tour invitation opened',
        detail: 'Admissions posted new times for Myra.',
        timestamp: 'Yesterday',
      },
    ],
  }
}
